name: Manual Deployment by Branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to deploy
        required: true
      env:
        description: Environment to deploy
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - qa
          - prod

jobs:
  deploy:
    name: Deploy branch ${{ github.event.inputs.branch }} to ${{ github.event.inputs.env }} env
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: yarn

      - name: Type Checking and Linting
        run: yarn check-lint-type

      - name: Run Tests
        run: yarn test --ci

      - name: Deploy to ${{ github.event.inputs.env }} environment
        run: yarn deploy --stage ${{ github.event.inputs.env }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
